### PR TITLE
improve HMR build time

### PR DESCRIPTION
**Pull request by victor-perkins226**

### CODE REVIEW

**Comment by yattias** [comment]
@victor-perkins226 can you include some banchmarks for before / after so we can compare the HMR speed difference?

**Comment by victor-perkins226** [comment]
@yattias Should I add benchmark on all pages or components?

**Comment by victor-perkins226** [comment]
I improved HMR by modifying next config.
I will add benchmark on each page, so that you can check loading time.

**Comment by yattias** [comment]
@victor-perkins226 Could be a video, description or screenshot of before and after speed improvements

**Comment by victor-perkins226** [comment]
That's good idea

**Comment by victor-perkins226** [comment]
Added benchmark and video

**Pull request closed without merging**
